apiVersion: apps/v1
kind: Deployment
metadata:
  name: highlander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highlander
  template:
    metadata:
      labels:
        app: highlander
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector: 
              matchExpressions:  
              - key: app
                operator: In
                values:
                - highlander
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80

