apiVersion: v1
kind: Pod
metadata:
  name: business-critical-app-amazon
spec:
  containers:
  - name: cnt
    image: nginx
    #nodeSelector:
    #disktype: premium-nvme
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: zones
            operator: In
            values:
            - antarctica-east1
            - antarctica-west1
