apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "app-db"
        operator: "Equal"
        value: "azure-file-storage"
        effect: "NoSchedule"
      containers:
      - name: web-container
        image: nginx:1.17
        ports:
        - containerPort: 80
