apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
        # securityContext:
          #  runAsUser: 1000
          # runAsGroup: 3000
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      privileged: true
