apiVersion: v1
kind: Pod
metadata:
  name: tls-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: tls-volume
          mountPath: /etc/tls
          readOnly: true

  volumes:
    - name: tls-volume
      secret:
        secretName: my-tls-secret
